apiVersion: v1
kind: Service
metadata:
  name: {{ template "graylog.fullname" . }}
  labels:
    name: graylog
    app: {{ template "graylog.name" . }}
    chart: {{ template "graylog.chart" . }}
    component: graylog-service-{{ .Release.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    graylog: "true"
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.graylog.web.service.externalPort }}
    targetPort: {{ .Values.graylog.web.service.internalPort }}
  - name: gelf-tcp-input
    protocol: TCP
    port: 12201
    targetPort: 12201
  - name: syslog-tcp-input
    protocol: TCP
    port: 1514
    targetPort: 1514
  type: NodePort
