

ingress:
  name: ingress
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx 
    
  hosts:
    - graylog.onpremise.dev.aws.csservice.de

  protocol: https
  domain:
#  proxyDomain:
  externalProtocol: https
  proxyProtocol: https
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

mongodbReplicaset:
  name: mongodb

mongodb-replicaset:
  name: mongodb
  metrics:
    enabled: true


elasticsearch:
  name: elasticsearch
  appVersion: "5.6.4"
  
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "5.6.4"

  cluster:
    xpackEnable: false
    env:
      xpack.security.enabled: 'false'
      XPACK_MONITORING_ENABLED: 'false'

  client:
    replicas: 2

  master:
    replicas: 3
    persistence:
      size: "4Gi"
      storageClass: "standard"

  data:
    replicas: 2
    persistence:
      size: "500Gi"
      storageClass: "standard"

elasticsearch-exporter:
  es:
    uri: "http://graylog-elasticsearch-client:9200"

graylog:
  name: graylog
  appVersion: 2.4.6

  image:
    repository: "arvatoaws/graylog"
    tag: "latest"

  passwordSecret:
  
  storageClass: "standard"

  web:
    service:
      externalPort: 80
      internalPort: 9000

  master:
    name: master
    replicaCount: 1

    affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - graylog-slave
            topologyKey: kubernetes.io/hostname

    containers:
      resources:
        requests:
          cpu: .25
          memory: 1536Mi
        limits:
          cpu: 1.5
          memory: 2048Mi

  slave:
    name: slave
    replicaCount: 2

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: component
              operator: In
              values:
              - graylog-master
          topologyKey: kubernetes.io/hostname

    containers:
      resources:
        requests:
          cpu: .25
          memory: 1536Mi
        limits:
          cpu: 1.5
          memory: 2048Mi
